# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
from abc import ABC


class Callback(ABC):
    # train
    def on_train_start(self, trainer): ...

    def on_train_end(self, trainer): ...

    def on_train_epoch_start(self, trainer): ...

    def on_train_epoch_end(self, trainer): ...

    def on_train_batch_start(self, trainer, batch): ...

    def on_train_batch_end(self, trainer): ...

    # validation
    def on_validation_start(self, trainer): ...

    def on_validation_batch_start(self, trainer, batch): ...

    def on_validation_batch_end(self, trainer, batch): ...

    def on_validation_end(self, trainer): ...

    # forward / backward / optimizer step
    def on_forward_start(self, trainer, batch): ...

    def on_forward_end(self, trainer, loss): ...

    def on_backward_start(self, trainer, loss): ...

    def on_backward_end(self, trainer): ...

    def on_optimizer_step_start(self, trainer): ...

    def on_optimizer_step_end(self, trainer): ...
