# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
import os
import subprocess
import sys
from pathlib import Path

import pandas as pd
import requests
import pytest
from training_test_cases import TRAINING_TEST_CASES
from error_messages import TOLERANCE_CHECK_WARNING_MESSAGE, CORRECTNESS_FAILURE_MESSAGE, TIMED_OUT_MESSAGE, RUN_ERROR_MESSAGE

LOG_DIR = Path("tests/training_logs")
GOLDEN_DIR = Path("tests/golden_files")

NOTIFICATION_TOKEN = os.getenv("NOTIFICATION_TOKEN")
NOTIFICATION_TOLERANCE = 0.1


def run_experiment(cmd: list[str], test_id: str, setup_dict: dict):
    """
    Run the main experiment script and report errors.

    Args:
        cmd: Command to run the experiment.
        test_id: ID of the test.
        setup_dict: Dictionary containing the test setup.
    """
    try:
        result = subprocess.run(
            cmd,
            cwd=str(Path.cwd()),
            timeout=setup_dict["timeout"],
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            error_msg = f"Exit code: {result.returncode}\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
            print(f"\n{'='*60}")
            print(error_msg)
            print(f"{'='*60}\n")
            send_notification(
                RUN_ERROR_MESSAGE.format(
                    test_id=test_id,
                    error=error_msg
                )
            )
            pytest.fail(f"Training script exited with code {result.returncode}")

    except subprocess.TimeoutExpired:
        send_notification(
            TIMED_OUT_MESSAGE.format(
                test_id=test_id,
                timeout=setup_dict['timeout']
            )
        )
        pytest.fail(f"Training script timed out after {setup_dict['timeout']} seconds")


def assert_loss_with_tolerance(log_file: str, golden_file: str, tolerance: float):
    log_df = pd.read_csv(log_file)
    golden_df = pd.read_csv(golden_file)
    pd.testing.assert_frame_equal(log_df, golden_df, rtol=tolerance)


def get_log_files() -> tuple[str, str]:
    """
    Get the names of the two most recently touched files in {LOG_DIR}.
    These are freshly generated by the test run.

    Returns:
        train_log_file: Name of the most recently touched train log file.
        val_log_file: Name of the most recently touched val log file.
    """

    os.makedirs(LOG_DIR, exist_ok=True)
    os.makedirs(GOLDEN_DIR, exist_ok=True)

    log_files = sorted(
        (f for f in LOG_DIR.iterdir() if f.is_file()),
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )

    most_recent_files = log_files[:2]
    train_log_file = None
    val_log_file = None
    for f in most_recent_files:
        name = f.name
        if "val" in name or "validation" in name:
            val_log_file = name
        elif "train" in name:
            train_log_file = name

    return train_log_file, val_log_file


def send_notification(message: str):
    if NOTIFICATION_TOKEN is None or NOTIFICATION_TOKEN == "":
        return
    
    token_parts = NOTIFICATION_TOKEN.split("_")
    assert all(part.isalnum() for part in token_parts), "NOTIFICATION_TOKEN is not a valid token!"
    token = "/".join(token_parts)

    # Remove lines starting with [index], [left], [right]
    # in order to avoid pollution on Slack.
    if message is not None:
        message = "\n".join(
            line for line in message.splitlines() if not line.lstrip().startswith('[')
        )

    requests.post(
        url=f"https://hooks.slack.com/triggers/{token}",
        json={"message": message},
    )


@pytest.mark.parametrize("setup_dict", TRAINING_TEST_CASES)
def test_training_script(
    setup_dict: dict,
    request: pytest.FixtureRequest,
):
    """
    Test that training script runs successfully with test configuration.

    Spawns subprocess to execute training script, verifies exit code 0.

    Args:
        setup_dict: Dictionary containing the test setup:
            - test_script: Path to the training script.
            - experiment_config: Path to the experiment configuration.
            - test_config: Path to the test configuration.
            - tolerance: Tolerance for loss and accuracy metrics.
            - timeout: Timeout in seconds.
        request: pytest request object.
    """

    default_setup_dict = {
        "test_script": None,
        "experiment_config": None,
        "test_config": "tests/configs/test_training_fast.yaml",
        "tolerance": 0.5,
        "timeout": 800.0,
    }

    setup_dict = default_setup_dict | setup_dict

    assert setup_dict["test_script"] is not None, "`test_script` is required."

    test_id = request.node.callspec.id

    assert Path(setup_dict["test_script"]).exists(), f"Script not found: {setup_dict['test_script']}"
    assert Path(setup_dict["test_config"]).exists(), f"Config not found: {setup_dict['test_config']}"

    cmd = [sys.executable, str(setup_dict["test_script"]), "--test-config", str(setup_dict["test_config"])]
    if setup_dict["experiment_config"] is not None:
        cmd.append("--config")
        cmd.append(str(setup_dict["experiment_config"]))

    run_experiment(cmd, test_id, setup_dict)

    train_log_file, val_log_file = get_log_files()

    if train_log_file is None or val_log_file is None:
        return  # If a test does not support golden files yet.

    if not os.path.exists(os.path.join(GOLDEN_DIR, train_log_file)):
        # Reference run, move the log files to golden_files.
        # Sleep to ensure the files are touched after the test run.
        os.rename(os.path.join(LOG_DIR, train_log_file), os.path.join(GOLDEN_DIR, train_log_file))
        os.rename(os.path.join(LOG_DIR, val_log_file), os.path.join(GOLDEN_DIR, val_log_file))
    else:
        # Test run, compare the train and val log files in training_logs with those in golden_files.
        try:
            assert_loss_with_tolerance(
                os.path.join(LOG_DIR, train_log_file),
                os.path.join(GOLDEN_DIR, train_log_file),
                tolerance=setup_dict["tolerance"],
            )
            assert_loss_with_tolerance(
                os.path.join(LOG_DIR, val_log_file),
                os.path.join(GOLDEN_DIR, val_log_file),
                tolerance=setup_dict["tolerance"],
            )
        except Exception as e:
            send_notification(
                CORRECTNESS_FAILURE_MESSAGE.format(
                    test_id=test_id,
                    error=str(e)
                )
            )
            pytest.fail(f"Loss curve mismatch: {str(e)}")
        
        try:
            assert_loss_with_tolerance(
                os.path.join(LOG_DIR, train_log_file),
                os.path.join(GOLDEN_DIR, train_log_file),
                tolerance=NOTIFICATION_TOLERANCE,
            )
            assert_loss_with_tolerance(
                os.path.join(LOG_DIR, val_log_file),
                os.path.join(GOLDEN_DIR, val_log_file),
                tolerance=NOTIFICATION_TOLERANCE,
            )
        except Exception as e:
            send_notification(
                TOLERANCE_CHECK_WARNING_MESSAGE.format(
                    test_id=test_id,
                    error=str(e)
                )
            )

        os.unlink(os.path.join(LOG_DIR, train_log_file))
        os.unlink(os.path.join(LOG_DIR, val_log_file))
