# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
import os
import subprocess
import sys
from pathlib import Path

import pandas as pd
import pytest
from training_test_cases import TRAINING_TEST_CASES

LOG_DIR = Path("tests/training_logs")
GOLDEN_DIR = Path("tests/golden_files")


def assert_loss_with_tolerance(log_file: str, golden_file: str, tolerance: float):
    log_df = pd.read_csv(log_file)
    golden_df = pd.read_csv(golden_file)
    pd.testing.assert_frame_equal(log_df, golden_df, rtol=tolerance)


def get_log_files() -> tuple[str, str]:
    """
    Get the names of the two most recently touched files in {LOG_DIR}.
    These are freshly generated by the test run.

    Returns:
        train_log_file: Name of the most recently touched train log file.
        val_log_file: Name of the most recently touched val log file.
    """

    os.makedirs(LOG_DIR, exist_ok=True)
    os.makedirs(GOLDEN_DIR, exist_ok=True)

    log_files = sorted(
        (f for f in LOG_DIR.iterdir() if f.is_file()),
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )

    most_recent_files = log_files[:2]
    train_log_file = None
    val_log_file = None
    for f in most_recent_files:
        name = f.name
        if "val" in name or "validation" in name:
            val_log_file = name
        elif "train" in name:
            train_log_file = name

    return train_log_file, val_log_file


@pytest.mark.parametrize("setup_dict", TRAINING_TEST_CASES)
def test_training_script(
    setup_dict: dict,
    request: pytest.FixtureRequest,
):
    """
    Test that training script runs successfully with test configuration.

    Spawns subprocess to execute training script, verifies exit code 0.

    Args:
        setup_dict: Dictionary containing the test setup:
            - test_script: Path to the training script.
            - experiment_config: Path to the experiment configuration.
            - test_config: Path to the test configuration.
            - tolerance: Tolerance for loss and accuracy metrics.
            - timeout: Timeout in seconds.
        request: pytest request object.
    """

    default_setup_dict = {
        "test_script": None,
        "experiment_config": None,
        "test_config": "tests/configs/test_training_fast.yaml",
        "tolerance": 0.5,
        "timeout": 800.0,
    }

    setup_dict = default_setup_dict | setup_dict

    assert setup_dict["test_script"] is not None, "`test_script` is required."

    test_id = request.node.callspec.id

    assert Path(setup_dict["test_script"]).exists(), f"Script not found: {setup_dict['test_script']}"
    assert Path(setup_dict["test_config"]).exists(), f"Config not found: {setup_dict['test_config']}"

    cmd = [sys.executable, str(setup_dict["test_script"]), "--test-config", str(setup_dict["test_config"])]
    if setup_dict["experiment_config"] is not None:
        cmd.append("--config")
        cmd.append(str(setup_dict["experiment_config"]))

    try:
        result = subprocess.run(
            cmd,
            cwd=str(Path.cwd()),
            timeout=setup_dict["timeout"],
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            print(f"\n{'='*60}")
            print(f"FAILED: {test_id}")
            print(f"Exit code: {result.returncode}")
            print(f"\nSTDOUT:\n{result.stdout}")
            print(f"\nSTDERR:\n{result.stderr}")
            print(f"{'='*60}\n")
            pytest.fail(f"Training script exited with code {result.returncode}")

    except subprocess.TimeoutExpired:
        pytest.fail(f"Training script timed out after {setup_dict['timeout']} seconds")

    train_log_file, val_log_file = get_log_files()

    if train_log_file is None or val_log_file is None:
        return  # If a test does not support golden files yet.

    if not os.path.exists(os.path.join(GOLDEN_DIR, train_log_file)):
        # Reference run, move the log files to golden_files.
        # Sleep to ensure the files are touched after the test run.
        os.rename(os.path.join(LOG_DIR, train_log_file), os.path.join(GOLDEN_DIR, train_log_file))
        os.rename(os.path.join(LOG_DIR, val_log_file), os.path.join(GOLDEN_DIR, val_log_file))
    else:
        # Test run, compare the train and val log files in training_logs with those in golden_files.
        assert_loss_with_tolerance(
            os.path.join(LOG_DIR, train_log_file),
            os.path.join(GOLDEN_DIR, train_log_file),
            tolerance=setup_dict["tolerance"],
        )
        assert_loss_with_tolerance(
            os.path.join(LOG_DIR, val_log_file),
            os.path.join(GOLDEN_DIR, val_log_file),
            tolerance=setup_dict["tolerance"],
        )

        os.unlink(os.path.join(LOG_DIR, train_log_file))
        os.unlink(os.path.join(LOG_DIR, val_log_file))
