experiment_name: nerf_bh_yaml_200
tags:
  - tt-forge-fe
  - model:torch
  - lightning

model:
  deg: 2
  in_channels_dir: 32
  num_freqs: 10
  coarse:
    depth: 4
    width: 128
    samples: 64
  fine:
    depth: 4
    width: 192
    samples: 8
  coord_scope: 3.0
  sigma_init: 30.0
  weight_threshold: 0.00001
  uniform_ration: 0.01
  beta: 0.1
  warmup_step: 0

data_loading:
  input_dir: /proj_sw/training_data/tt_nerf_white
  img_wh: [200, 200]
  batch_size: 4096

training:
  use_forge: True
  device: cpu
  val_only: False
  epochs: 16
  loss: mse
  optimizer: adam
  optimizer_kwargs:
    lr: 0.0005
    weight_decay: 0.0005
  warmup_multiplier: 1.0
  warmup_epochs: 0
  log_every: 50
