name: TT-Forge-FE Nighty Uplift

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 08:00 UTC every day
  workflow_dispatch:  # Manual trigger

jobs:
  get-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.get-docker-tag.outputs.docker-tag }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Fetch all history and tags
          ref: main

      - name: Get the latest docker tag
        id: get-docker-tag
        run: .\third_party\tt-forge-fe\.github\get-docker-tag.sh

  uplift-ffe:
    needs: get-docker-tag
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.get-docker-tag.outputs.docker-tag }}

    env:
      SUBMODULE_PATH: third_party/tt-forge-fe
      SUBMODULE_VERSION: origin/main

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Fetch all history and tags
          ref: main

      # Run tests before uplift
      - name: Run Test
        shell: bash
        run: |
          source env/activate
          python thomas/test/tt-forge-fe/test_mnist.py

      # If tests successful, uplift the submodule
      - name: Set env variable
        if: success()
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update submodule
        run: |
            cd $SUBMODULE_PATH
            git fetch origin
            git checkout $SUBMODULE_VERSION
            echo "### Latest commit in $SUBMODULE_PATH ###"
            git log -1
            cd ../..

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create-pr
        with:
          branch: uplift
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          base: main
          commit-message: "Uplift ${{ env.SUBMODULE_PATH }} to ${{ env.SUBMODULE_VERSION }} ${{ env.TODAY }}"
          title: "Uplift ${{ env.SUBMODULE_PATH }} to ${{ env.SUBMODULE_VERSION }} ${{ env.TODAY }}"
          body: "This PR uplifts the ${{ env.SUBMODULE_PATH }} submodule to the ${{ env.SUBMODULE_VERSION }}"
          labels: uplift
          delete-branch: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Approve Pull Request
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_APPROVE_TOKEN }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
          gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve

      - name: Enable Pull Request Automerge
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
